[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
license = "BSD-3-Clause"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
chrono = { version = "0.4.26", features = [
    "std",
    "clock",
    "serde",
], default-features = false } # for timestamps
console = "0.15.7" # colour stderr logging
http = "0.2.9"
httptest = "0.15.4"
lazy_static = "1.4.0"
log = { version = "0.4.19", features = ["std"] }
parking_lot = "0.12.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
serde_with = "3.0.0"
tokio = "1.29.1"
toml = "0.7.6"
uuid = { version = "1.4.1", features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.11.18", default-features = false, features = [
    "blocking",
    "rustls",
] }

[features]
ci = []
