[package]
name = "test_helpers"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
license = "BSD-3-Clause"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
chrono = { version = "0.4.24", features = [
    "std",
    "clock",
    "serde",
], default-features = false } # for timestamps
console = "0.15.5" # colour stderr logging
http = "0.2.8"
httptest = "0.15.4"
lazy_static = "1.4.0"
log = { version = "0.4.17", features = ["std"] }
parking_lot = "0.12.1"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
serde_with = "2.3.1"
tokio = "1.26.0"
toml = "0.7.3"
uuid = { version = "1.1.2", features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.11.11", default-features = false, features = [
    "blocking",
    "rustls",
] }

[features]
ci = []
