pub const ENV_LOG_FILE: &str = "PEXSHELL_LOG_FILE";
pub const ENV_LOG_LEVEL: &str = "PEXSHELL_LOG_LEVEL";
pub const ENV_LOG_TO_STDERR: &str = "PEXSHELL_LOG_TO_STDERR";
pub const ENV_USER_ADDRESS: &str = "PEXSHELL_ADDRESS";
pub const ENV_USER_USERNAME: &str = "PEXSHELL_USERNAME";
pub const ENV_USER_PASSWORD: &str = "PEXSHELL_PASSWORD";

pub const EXIT_CODE_INTERRUPTED: i32 = 130;
