name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-native:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: release-build
          cargo-install: cargo-nextest
      - name: Build
        run: cargo build --workspace --release --locked --verbose
      - name: Test
        run: cargo nextest run --workspace --release --locked
      - uses: ./.github/actions/upload-artifact
        with:
          name: release build ${{ matrix.os }}
          path-nix: target/release/pexshell
          path-windows: target/release/pexshell.exe
     
