name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  native:
    strategy:
      matrix:
        include:
          - name: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - name: x86_64-apple-darwin
            os: macos-latest
          - name: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: release-build
          cargo-install: cargo-nextest
          rust-targets: ${{ matrix.name }}
      - name: Build
        run: cargo build --workspace --release --locked --verbose --target ${{ matrix.name }}
      - name: Test
        run: cargo nextest run --workspace --release --locked --target ${{ matrix.name }}
      - uses: ./.github/actions/upload-artifact
        with:
          artifact-name: ${{ matrix.name }}
          path-nix: target/release/pexshell
          path-windows: target/release/pexshell.exe
     
  cross:
    strategy:
      matrix:
        include:
          - name: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - name: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: release-build-${{ matrix.name }}
          cargo-install: cross
          rust-targets: ${{ matrix.name }}
      - name: Build
        run: cross build --workspace --release --locked --verbose --target ${{ matrix.name }}
      - uses: ./.github/actions/upload-artifact
        with:
          artifact-name: ${{ matrix.name }}
          path-nix: target/release/pexshell
          path-windows: target/release/pexshell.exe
