name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  native:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: release-build-${{ matrix.target }}
          cargo-install: cargo-nextest
          rust-targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --workspace --release --locked --verbose --target ${{ matrix.target }}
      - name: Test
        run: cargo nextest run --workspace --release --locked --target ${{ matrix.target }}
      - uses: ./.github/actions/upload-artifact
        with:
          artifact-name: ${{ matrix.target }}
          path-nix: target/${{ matrix.target }}/release/pexshell
          path-windows: target/${{ matrix.target }}/release/pexshell.exe

  cross:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: release-build-${{ matrix.target }}
          cargo-install: cross
          rust-targets: ${{ matrix.target }}
      - name: Build
        run: cross build --workspace --release --locked --verbose --target ${{ matrix.target }}
      - uses: ./.github/actions/upload-artifact
        with:
          artifact-name: ${{ matrix.target }}
          path-nix: target/${{ matrix.target }}/release/pexshell
          path-windows: target/${{ matrix.target }}/release/pexshell.exe
