name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: [1.64.0, stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: cargo-build
          rust-version: ${{ matrix.rust-version }}
      - name: Install dependencies
        run: cargo install cargo-nextest
      - name: Build
        run: cargo build --workspace --release --locked --verbose
      - name: Test
        run: cargo nextest run --workspace --release --locked
      - name: Upload build [-nix]
        if: (matrix.os != 'windows-latest') && (matrix.rust-version == 'stable')
        uses: actions/upload-artifact@v3
        with:
          name: release build ${{ matrix.os }}
          path: target/release/pexshell
          retention-days: 7
          if-no-files-found: error
      - name: Upload build [Windows]
        if: (matrix.os == 'windows-latest') && (matrix.rust-version == 'stable')
        uses: actions/upload-artifact@v3
        with:
          name: release build ${{ matrix.os }}
          path: target/release/pexshell.exe
          retention-days: 7
          if-no-files-found: error
