name: Check

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: clippy
      - name: Clippy
        run: cargo clippy --workspace --locked --tests

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: nobuild
      - name: Check formatting
        run: rustc --version && cargo --version && cargo fmt --all --check

  # Disabled due to https://github.com/DevinR528/cargo-sort/issues/47
  # sort:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/prepare
  #       with:
  #         cache-id: nobuild
  #         cargo-install: cargo-sort
  #     - run: cargo sort --check --workspace
