name: CI

on:
  pull_request:
  merge_group:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  check:
    uses: ./.github/workflows/check.yml
  dependencies:
    uses: ./.github/workflows/dependencies.yml
  test:
    uses: ./.github/workflows/test.yml
