name: Dependencies

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  advisories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: nobuild
          cargo-install: cargo-deny
      - name: Check for security advisories and unmaintained crates
        run: cargo deny check advisories

  bans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: nobuild
          cargo-install: cargo-deny
      - name: Check for banned and duplicated dependencies
        run: cargo deny check bans

  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: nobuild
          cargo-install: cargo-about
      - name: Generate license summary
        run: cargo about generate about.hbs > licenses.html
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: licenses
          path: licenses.html
          retention-days: 30

  sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: nobuild
          cargo-install: cargo-deny
      - name: Checked for unauthorized crate sources
        run: cargo deny check sources
