name: Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: debug-build
          rust-version: nightly
          rust-components: llvm-tools-preview
          cargo-install: cargo-nextest,cargo-llvm-cov
      - name: Run tests
        run: cargo llvm-cov --workspace --locked nextest --html --features ci
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: target/nextest/default/report.xml
          retention-days: 30
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: target/llvm-cov/
          retention-days: 30

  msrv:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          cache-id: debug-build
          rust-version: 1.66
          cargo-install: --locked:--vers:0.9.50:cargo-nextest
      - name: Build
        run: cargo build --workspace --locked --verbose
      - name: Test
        run: cargo nextest run --workspace --locked
